server {
    listen 80;
    server_name site2.local;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        root /var/www/site2;
        index index.html;
    }
}
