server {
    listen 80;
    server_name site1.54.233.211.29.nip.io;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        root /usr/share/nginx/html/site1;
        index index.html;
    }
}
